export const unilac = [
  {
    id: 1,
    image: "../src/assets/images/upg.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 2,
    image: "../src/assets/images/upg1.jpeg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 3,
    image: "../src/assets/images/upg.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 4,
    image: "../src/assets/images/upg.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 5,
    image: "../src/assets/images/upg.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 6,
    image: "../src/assets/images/upg.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 7,
    image: "../src/assets/images/upg.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 8,
    image: "../src/assets/images/upg.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
];
export const orient = [
  {
    id: 1,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 2,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 3,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 4,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 5,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 6,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 7,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 8,
    image: "../src/assets/images/upg2.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
];
export const unitex = [
  {
    id: 1,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 2,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 3,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 4,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 5,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 6,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 7,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 8,
    image: "../src/assets/images/unitex.png",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
];
export const premier = [
  {
    id: 1,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 2,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 3,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 4,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 5,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 6,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 7,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
  {
    id: 8,
    image: "../src/assets/images/premier.jpg",
    title: "Unilac UPG",
    description: "Glow",
    price: "4000",
  },
];
